# Generated by Django 5.0.6 on 2024-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='uom',
            table='uom',
        ),
    ]
