# Generated by Django 5.0.6 on 2024-05-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_table_alter_uom_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uom_id',
            new_name='uom',
        ),
    ]
