# Generated by Django 5.0.6 on 2024-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=122)),
                ('total_cost', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
