# Generated by Django 5.0.6 on 2024-05-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_detail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_detail',
            table='Order_detail',
        ),
    ]
